# Generated by Django 5.1.1 on 2025-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
