# Generated by Django 5.1.1 on 2025-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
