# Generated by Django 3.2 on 2025-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
