# Generated by Django 5.1.6 on 2025-05-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('album_cover', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_cover',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_title',
        ),
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del álbum'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('artist_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'unique_together': {('user_id', 'song', 'album', 'artist_id')},
            },
        ),
    ]
