# Generated by Django 5.1.6 on 2025-05-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_remove_song_album_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='song_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_comments', to='music.song'),
        ),
    ]
