# Generated by Django 5.1.6 on 2025-05-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_comments_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='album_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_comments', to='music.album'),
        ),
    ]
