# Generated by Django 5.1.6 on 2025-05-03 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_remove_song_album_cover_and_more'),
        ('store', '0003_alter_order_options_alter_purchase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'song')},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='music.album'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.album'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('song', 'Canción'), ('album', 'Álbum')], default='song', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_album_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.album'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='music.song'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.song'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.song'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'album'), ('user', 'song')},
        ),
        migrations.CreateModel(
            name='AlbumPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.album')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'album')},
            },
        ),
    ]
