# Generated by Django 5.1.6 on 2025-04-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist_name_user_artist_type_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
