# Generated by Django 5.1.6 on 2025-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_song_file'),
        ('user', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/usuario.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.song'),
        ),
    ]
