# Generated by Django 5.1.6 on 2025-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_remove_song_album_cover_and_more'),
        ('user', '0005_user_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.album'),
        ),
    ]
